### ISSUE TITLE
DB Layout - mehrere Tabellen

### ISSUE THREAD

**Issue by marlon360** [ar-exhibition/cms#1]
Um das Datenbank Layout etwas zu verbessern, könnte man Daten, die sich wiederholen in eigene Tabellen überführen und mit Foreign Keys arbeiten.

User Table:
Id, Vorname, Nachname, Studiengang

Kurs Table:
Id, Studiengang, Kurs

Asset Table
FK User, FK Kurs, Datum, Dateiart, Link, Semester

**Comment by marlon360** [comment]
@TheCanadians @codebaard Was ist eure Meinung dazu?

**Comment by codebaard** [comment]
Ich bin geteilter Meinung. Also: Die Idee finde ich grundsätzlich super. Gar nichts dagegen einzuwenden. Einzig vor dem Hintergrund von "Keep it simple" sehe ich derzeit noch nicht den Mehrwehrt das Datenbanklayout komplexer zu gestalten als notwendig.
Hätte das positive Auswirkungen auf die Gestaltung der App?

PS: entschuldigt die inaktivität gestern + vorgestern. Hab aufgrund der tropischen temperaturen in meiner Wohnung keine konzentrierte Minute gefunden. :-D

**Comment by TheCanadians** [comment]
Das war auch mein Gedanke beim Layout. Klar kann man das Ganze in mehrere Tabellen aufteilen, aber ich habe keinen direkten Mehrwert darin gesehen. Aber wollte da eh nochmal mit euch drüber quatschen, da ich nicht sicher weiß wie wir uns das auf App-Seite vorstellen auf die DB zuzugreifen.

**Comment by marlon360** [comment]
Die sogenannte "Normalisierung" ist ein standardisiertes Verfahren, dass die Integrität einer Datenbank sichert und Redundanz vermeidet (https://en.wikipedia.org/wiki/Database_normalization). Normalerweise wird dazu zuerst ein Entity-Relationship-Model angefertigte und daraus die Tabellen abgeleitet.

Durch dieses Verfahren können wir in einer wissenschaftlichen Dokumentation unser Datenbank Layout mit Quellen begründen.

Konkrete Vorteile:
Die Datenbank wird flexibel. Ein Beispiel hierfür wäre wenn mehr als eine Person an einem Projekt gearbeitet haben.
Änderungen sind konsistent über alle Einträge. Wenn sich redundante Daten ändern, müssen sie an allen Stellen geändert werden.
Unabhängigkeit von Strings. Es muss irgendwie gesichert sein, dass eindeutige Name immer konsistent sind. Beispiel: Digital Reality, DR, digital reality. Wenn wir in der App nach Studiengang filtern wollen, ist es gut, wenn schon in der Datenbank ein eindeutiger Eintrag pro Studiengang vorhanden ist.

**Comment by TheCanadians** [comment]
Macht Sinn. Stimme zu das Datenbank-Layout dementsprechend zu ändern.

**Comment by codebaard** [comment]
_Unabhängigkeit von Strings. Es muss irgendwie gesichert sein, dass eindeutige Name immer konsistent sind._
Das lässt sich einfacher lösen: MVC bietet die Möglichkeit jedes Feld auf Plausibilität zu prüfen bzw. wir können einfach via Dropdown derartige Felder (Studiengang, Fach, etc) vorgeben. 

_Redundanz von Daten_ wäre nach meinem Dafürhalten das einzig sinnvolle Argument. Denkt man dann aber einen Schritt weiter, müssen wir dann wiederum sicherstellen, dass jeder User seinen Namen immer auf die gleiche Weise eingibt: "Finn-Ole" vs "Finn Ole" oder mit Nutzerkonto, etc. anfangen. Man könnte auch nach Matrikelnummern filtern aber was ist, wenn jemand etwas hochlädt, der von extern kommt? (z.b. Anke vdh möchte gerne Model XY aus ihrem Projekt ebenfalls zeigen).

_Wissenschaftliche Dokumentation:_
Ich sehe nichts verwerfliches daran, das in der Dokumentation zu erwähnen und ausführlich über Datenbanklayouts zu quatschen und am Ende zu sagen "alles schön und gut, aber ist unnötig kompliziert für die Anwendung". (sic!).

**Bottom Line:**
Ich sehe keinen Mehrwert sondern nur Mehrarbeit. Allerdings ist das aus meiner Perspektive schwer zu argumentieren, wenn ich angekündigt hab, mich an nativer WebGL programmierung zu probieren. Insofern: Ich baue das gern ein. Würde das dann auf den nächsten Meilenstein setzen, wenn das MockUp steht. Das wird ja eh erstmal nur mit Dummy-Daten befüllt und geht um das Look and Feel und nicht um Content.

**Comment by marlon360** [comment]
> MVC bietet die Möglichkeit jedes Feld auf Plausibilität zu prüfen bzw. wir können einfach via Dropdown derartige Felder (Studiengang, Fach, etc) vorgeben.

Das würde heißen, dass die Möglichkeiten für Studiengang, Fach, etc hard-coded im Backend vorhanden sein müssen. Eine Tabelle würde in Hinblick auf die Wartbarkeit Sinn machen. Server Code muss nicht neu deployed werden, wenn sich Daten ändern.

> [...] müssen wir dann wiederum sicherstellen, dass jeder User seinen Namen immer auf die gleiche Weise eingibt

Das gleiche "Problem" hätten man dann ja auch ohne zusätzliche Tabelle, da man dann ja auch den Namen immer gleich eingeben muss. Sonst muss der Kurator selbst einschätzen, ob die Dateien zum gleichen Nutzer gehören, trotz unterschiedlicher Schreibweise.
BTW: Würde eine E-Mail Adresse als eindeutige Identifikation vorschlagen. Man kann voraussetzen, dass jeder Nutzer eine E-Mail Adresse hat.

Ich habe meine Bedenken geäußert, da ich das Gefühl habe, dass der Server auch über unser Projekt hinaus genutzt werden könnte. Zum Beispiel von anderen Anwendungen wie der VR-App. Deswegen sollte man schon in der untersten Schicht über Erweiterbarkeit und Wartbarkeit nachdenken.

Da unser Projekt aber nicht primär auf das CMS fokussiert ist, können wir das auch vernachlässigen. Am Ende geht es ja nur darum auf irgendeine Art und Weise Daten in die AR-App zu kriegen.

**Comment by codebaard** [comment]
Created Database accordingly. See commit https://github.com/ar-exhibition/cms/commit/ad835ca4b4a2c6992029d5f36e7ad4c36c1373d6 for more information.
